[book]
authors = ["Charles Chege"]
language = "en"
multilingual = false
src = "src"
title = "Sea-ORM Simple CRUD Operations"

[output.html]
mathjax-support = true
site-url = "/sea-orm-tutorial/"
git-repository-url = "https://github.com/SeaQL/sea-orm-tutorial"
edit-url-template = "https://github.com/SeaQL/sea-orm-tutorial/edit/master/SimpleCRUD/book/{path}"
