//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0
pub use super::todo_list::{
    ActiveModel as MyTodosActiveModel, Column as MyTodosColumn, Entity as MyTodos,
    Model as MyTodosModel, PrimaryKey as MyTodosPrimaryKey, Relation as MyTodosRelation,
};
