[book]
authors = ["Charles Chege"]
language = "en"
multilingual = false
src = "src"
title = "TODO App"

[output.html]
mathjax-support = true
default-theme = "navy"
preferred-dark-theme = "navy"
site-url = "/sea-orm-tutorial/"
git-repository-url = "https://github.com/SeaQL/sea-orm-tutorial/tree/master/todo-app"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/SeaQL/sea-orm-tutorial/edit/master/todo-app/book/{path}"
