//! SeaORM Entity. Generated by sea-orm-codegen 0.6.0

pub use super::todos::{
    ActiveModel as TodosActiveModel, Column as TodosColumn, Entity as Todos, Model as TodosModel,
    PrimaryKey as TodosPrimaryKey, Relation as TodosRelation,
};
