name: Deploy

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install mdbook
        run: (test -x $HOME/.cargo/bin/mdbook || cargo install --debug --vers "^0.4" mdbook)
      - name: Install static-sitemap-cli
        run: npm install static-sitemap-cli

      # Build tutorials-book mdbook
      - name: Build tutorials-book mdbook
        run: mdbook build tutorials-book -d ../gh-pages
      - name: Generate tutorials-book sitemap
        run: |
          cd gh-pages
          npx sscli --base https://www.sea-ql.org/sea-orm-tutorial

      # Deploy GitHub Pages
      - name: Deploy GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: gh-pages
          single-commit: true
          clean: true
