name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # Try to build all examples
      - name: Build simple-crud example
        run: cargo build --manifest-path simple-crud/Cargo.toml
      - name: Build todo-app example
        run: cargo build --manifest-path todo-app/Cargo.toml

      # Try to build mdbooks
      - name: Install mdbook
        run: (test -x $HOME/.cargo/bin/mdbook || cargo install --debug --vers "^0.4" mdbook)
      - name: Build tutorials-book mdbook
        run: mdbook build tutorials-book
