name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build, Test & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.4" mdbook)
      - run: mdbook build SimpleCRUD/book
      # - run: mdbook test SimpleCRUD/book
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: SimpleCRUD/book/book