name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install mdbook
        run: (test -x $HOME/.cargo/bin/mdbook || cargo install --debug --vers "^0.4" mdbook)

      # Build simple-crud mdbook
      - name: Build simple-crud mdbook
        run: mdbook build simple-crud/book

      # Build todo-app mdbook
      - name: Build todo-app mdbook
        run: mdbook build todo-app/book
