name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install mdbook
        run: (test -x $HOME/.cargo/bin/mdbook || cargo install --debug --vers "^0.4" mdbook)

      # Build SimpleCRUD mdbook
      - name: Build SimpleCRUD mdbook
        run: mdbook build SimpleCRUD/book

      # Build SeaORM-TODO-App mdbook
      - name: Build SeaORM-TODO-App mdbook
        run: mdbook build SeaORM-TODO-App/book